version: '3.8'
services:
  java_app:
    container_name: java_app
    image: java_app:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
    #restart: always

  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: demo
    volumes:
      - pgdata:/var/lib/postgresql/data
    #restart: always
volumes:
  pgdata: { }